version: '3'

services:
    redis01:
        image: redis:4.0.14
        container_name: redis01
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6379:6379
            - 16379:16379
        volumes:
            - ./data/redis01/data:/var/lib/redis
            - ./data/redis01/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.11
    redis02:
        image: redis:4.0.14
        container_name: redis02
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6380:6379
            - 16380:16379
        volumes:
            - ./data/redis02/data:/var/lib/redis
            - ./data/redis02/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.12
    redis03:
        image: redis:4.0.14
        container_name: redis03
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6381:6379
            - 16381:16379
        volumes:
            - ./data/redis03/data:/var/lib/redis
            - ./data/redis03/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.13
    redis04:
        image: redis:4.0.14
        container_name: redis04
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6382:6379
            - 16382:16379
        volumes:
            - ./data/redis04/data:/var/lib/redis
            - ./data/redis04/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.14
    redis05:
        image: redis:4.0.14
        container_name: redis05
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6383:6379
            - 16383:16379
        volumes:
            - ./data/redis05/data:/var/lib/redis
            - ./data/redis05/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.15
    redis06:
        image: redis:4.0.14
        container_name: redis06
        sysctls:
            - net.core.somaxconn=4096
        command:
            - /usr/local/bin/redis-server
            - /data/redis.conf
        ports:
            - 6384:6379
            - 16384:16379
        volumes:
            - ./data/redis06/data:/var/lib/redis
            - ./data/redis06/redis.conf:/data/redis.conf
        networks:
            redis_cluster_net:
                ipv4_address: 172.28.0.16
networks:
    redis_cluster_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
